version: '3.7'

services:
  db:
    image: mysql:8
    container_name: db
    restart: always
    volumes:
      - ~/mysql-data:/var/lib/mysql
    environment:
      MSQL_ROOT_PASSWORD: pass
      MSQL_DATABASE: demo
      MSQL_USER: test
      MYSQL_PASSWORD: pass
    ports:
      - 3307:3306

#  phpmyadmin:
  #    image: phpmyadmin
  #    container_name: phpmyadmin
  #    restart: always
  #    ports:
  #      - 8081:80
  #    depends_on:
  #      - db

  php:
    image: php:8.2-apache
    container_name: php8.2
    volumes:
        - ./php:/var/www/html
    build:
        context: Dockerfile


  nginx:
      image: nginx:latest
      container_name: nginx
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./site.conf:/etc/nginx/conf.d/default.conf
        - ./www:/var/www/html
        - ./letsencrypt:/etc/letsencrypt
        - ./certbot-www:/var/www/certbot
      depends_on:
        - php-fpm
        - certbot
      networks:
        - mynetwork

  php-fpm:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: php-fpm
      volumes:
        - ./www:/var/www/html
      networks:
        - mynetwork

  mysql:
      image: mysql:5.7
      container_name: mysql
      environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: mydatabase
        MYSQL_USER: user
        MYSQL_PASSWORD: password
      volumes:
        - mysql-data:/var/lib/mysql
      networks:
        - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
        PMA_HOST: mysql
        MYSQL_ROOT_PASSWORD: rootpassword
    ports:
        - "8080:80"
    depends_on:
        - mysql
    networks:
        - mynetwork

  certbot:
      image: certbot/certbot
      container_name: certbot
      volumes:
        - ./letsencrypt:/etc/letsencrypt
        - ./certbot-www:/var/www/certbot
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
      networks:
        - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data:
  letsencrypt:
  certbot-www:

