version: '3.7'

services:
  db:
    image: mysql:8
    container_name: db
    restart: always
    volumes:
      - ~/mysql-data:/var/lib/mysql
    environment:
      MSQL_ROOT_PASSWORD: pass
      MSQL_DATABASE: demo
      MSQL_USER: test
      MYSQL_PASSWORD: pass
    ports:
      - 3307:3306

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    depends_on:
      - db

  php:
    image: php:8.2-apache
    container_name: php8.2
    ports:
      - 8080:80
    volumes:
        - ./php:/var/www/html
    build:
        context: Dockerfile

  nginx:
   image: nginx:1.15.0-alpine
   volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf:ro

   ports:
    -  8089:80
    - 443:443