index:
    uri: /home
    controller: Controller\HomeController
    httpMethod: [GET]

encrypt:
    uri: /encrypt
    controller: Controller\EncryptController
    httpMethod: [GET,POST]

decrypt:
    uri: /decrypt
    controller: Controller\DecryptController
    httpMethod: [GET,POST]

inscription:
    uri: /inscription
    controller: Controller\InscriptionController
    httpMethod: [GET,POST]

connexion:
    uri: /connexion
    controller: Controller\ConnexionController
    httpMethod: [GET,POST]

welcome:
    uri: /welcome
    controller: Controller\WelcomeController
    httpMethod: [GET, POST]

ErrorMail:
    uri: /errorMail
    controller: Controller\ErrorMailController
    httpMethod: [GET, POST]

api:
    uri: /api
    controller: Controller\RecupAPIController
    httpMethod: [GET,POST]
