index:
    uri: /
    controller: Controller\HomeController
    httpMethod: [GET]
jacki:
    uri: /jacki
    controller: Controller\JackiController
    httpMethod: [GET, POST]
hello:
    uri: /hello
    controller: Controller\HelloController
    httpMethod: [GET]
